### PR TITLE
#32 Work on changing object ownership

### PR DESCRIPTION
**Pull request by fcooper8472**

### CODE REVIEW

**Comment by fcooper8472** [comment]
This introduces a failing test.
```
/home/fergus/GitRepos/trase/tests/TestAxis.cpp:92: FAILED:
  CHECK( plot1->get_label() == "plot1" )
with expansion:
  "" == "plot1"
```
Spent half an hour debugging but no idea why the label becomes empty.  Probably doing something silly!  Any ideas @martinjrobins?

**Comment by martinjrobins** [comment]
ahh, I see it now. When you add the second plot, it does an `emplace_back` on the vector of plots, which can re-allocate the memory, invalidating your pointer to the first plot.

Might want to use a list instead?

Also, I'm having second thoughts about returning a pointer from `plot`, the consensus here (https://stackoverflow.com/questions/20091046/what-should-a-c-getter-return) is that we should return a reference, as you should only ever return a pointer if the return value could be null. What do you think?

**Comment by martinjrobins** [comment]
hmmm, cpp core guidline are not particularly helpful (just "Carefully Consider Your Return Types")

https://github.com/lefticus/cppbestpractices/blob/master/04-Considering_Safety.md

Seems like no-one actually knows the best way to write a C++ getter ;)

**Comment by fcooper8472** [comment]
Yeah, all good points.  Having had more time to think about this, perhaps the VTK-style `shared_ptr` for everything isn't a bad option:

- Getters return a `shared_ptr`: no worries about the user inadvertently getting a copy
- Semantics are the same for all objects in the hierarchy: avoids having `fig.axis()` but `ax->plot()`
- It's not as though we'll have more than a few such objects, so there's no realistic overhead from the ref count

What are your thoughts? I think my vote might go to `shared_ptr` after all...

**Comment by martinjrobins** [comment]
yea, I think this might be the way to go. I don't really like having to allocate memory, (or type `->`), but I don't think there is a better alternative. Plus, a nice thing about using pointers everywhere is that, for example, multiple axis can share the same plot, or multiple figures the same axis.

**Pull request closed without merging**
