### PR TITLE
#131 add contributing.md

### LINKED ISSUE #131: add contributing.md

### PR DESCRIPTION
**Pull request by martinjrobins**
Fixes #131 

- also snuck in a minor fix to the url for the rectangle example

### CODE REVIEW

**Comment by fcooper8472** [comment]
Travis failure seems suspicious?

**Comment by martinjrobins** [comment]
yea. The site that we use to download the iris dataset is currently down, which is causing the travis failure :(

**Comment by fcooper8472** [comment]
Ah, ok.  We ought to be able to cache data with travis, I'll look into it.

**Comment by martinjrobins** [comment]
its back now, so I'll merge

**Pull request merged**
