### PR TITLE
Implement svg backend unit tests

### PR DESCRIPTION
**Pull request by fcooper8472**

### CODE REVIEW

**Comment by fcooper8472** [comment]
Not ready for merging yet, but any thoughts on this kind of approach @martinjrobins?

**Comment by martinjrobins** [comment]
I think at the moment the test is a bit fragile, one whitespace change and the test falls over. How about search that, for example "<desc>r@ndom^name</desc>" exists in the output and the result is valid svg?

**Comment by fcooper8472** [comment]
Ok, or, taking it up one level from that, strip all the whitespace out of the strings and check that they're equal, and that it can form part of a valid svg?

How can we test that an svg is valid?

**Comment by martinjrobins** [comment]
The travis build looks for .svg files produced as part of the tests (in the current dir) and runs them through an svg validator program. So just write out .svg files as part of each test, and they will be validated once the tests finish

**Comment by fcooper8472** [comment]
@martinjrobins The strings are now compared after stripping all whitespace, then an svg is written out to the build directory.

The reason I'm not too keen on just checking whether substrings exist in the output is that we may legitimately one day change, say, the `function tooltip`, and that ought to be a test failure if we don't also change the unit test.

**Comment by martinjrobins** [comment]
The problem with comparing the whole string like that is that the test depends on the implementation. You should be able to write the test purely from the class/function documentation and declaration. As long as the class/function does what it says on the tin, it shouldn't matter what the particular implementation is.

For example, the following two strings full-fill perfectly what we would expect from the `rect` call:

```svg
<rect x="1.23" y="2.34" width="2.22" height="3.33" fill="#000000" fill-opacity="1.000000" stroke="#000000" stroke-opacity="1.000000" stroke-width="1.000000"/>
```

```svg
<rect  y="2.34" width="2.22" x="1.23" height="3.33"  fill-opacity="1.000000" stroke="#000000"  stroke-width="1.000000" stroke-opacity="1.000000" fill="#000000"/>
```

So they should both pass the test.

**Comment by fcooper8472** [comment]
I see what you're saying, and I'm almost convinced, but:
```
height="3.33"
```
```
height ="3.33"
```
```
height= "3.33"
```
```
height = "3.33"
```
```
height = "3.330"
```
will all produce valid svg that display identically.  So even if we test substrings we're still testing our implementation rather than our interface, it just changes the level at which we're looking.

**Comment by martinjrobins** [comment]
yea, agreed. I like the idea of stripping whitespace, which will solve many of those options. If we had the inclination we could write the test so that it would match all those numbers as well, and this is what I would do in an ideal world. But we need to strike a balance between writing a perfect test that purely tests functionality, and a "good enough" test that doesn't fail (unnecessarily) too much and create additional work.

**Comment by fcooper8472** [comment]
@martinjrobins probably won't add much to this PR for a little bit, so feel free to merge if you're happy with things

**Comment by martinjrobins** [comment]
Yup, I'm happy with these changes, merging now

**Pull request merged**
