### PR TITLE
#63 move implementation in Data.hpp to Data.cpp and Data.tcc

### PR DESCRIPTION
**Pull request by martinjrobins**
Note: I've used the extension `.tcc` for template implementations

### CODE REVIEW

**Comment by fcooper8472** [comment]
What's the rationale for separating the templated methods into a `.tcc` file rather than implementing them in the `.cpp`?

**Comment by martinjrobins** [comment]
If you implement them in the cpp you have to use explicit instantiation to compile them (into the object file). But if you don't know all the types you want to instantiate then the alternative is the put the implementation in the header file, or a separate template implementation file. The latter is the route I took, so that the functions support any type (that can be converted to a float). The choice of extension is arbitrary, I chose `tcc` cause it was the first one I tried that was detected as a c++ file by vim.

Note that the `Data.tcc` file is included at the end of the `Data.hpp` file. Also note that changing the implementation of the template functions is effectively changing a header file, so everything gets compiled.

**Comment by martinjrobins** [comment]
ahhhh, but this one

```cpp
template <typename Aesthetic>
+ColumnIterator DataWithAesthetic::end(const Aesthetic &a) {
```

should probably be moved to the cpp file, since we know all the possible Aesthetics. I will fix this...

**Comment by fcooper8472** [comment]
Ah, ok! That's neat.  I missed the `#include "Data.tcc"`

That all looks fine to me: do you want to move the `template <typename Aesthetic>` to the cpp file and I'll merge?

**Comment by martinjrobins** [comment]
I might leave the `template <typename Aesthetic>` to issue #66, and do it with that, so feel free to merge now.

**Pull request merged**
